services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  transactionapi:
    build:
      context: .
      dockerfile: transactionAPI/Dockerfile
    container_name: transaction.api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      database:
        condition: service_healthy
